name: Base Styles
description: Base styles for the Creative theme
type: core

form:
  fields:

    background:
      type: input.colorpicker
      label: Base Background
      default: "#ffffff"
    text-color:
      type: input.colorpicker
      label: Base Text Color
      default: "#666666"
    background-image:
      type: input.imagepicker
      label: Background Image
      default: "gantry-media://backgrounds/header/img-01.jpg"
    background-size:
      type: input.text
      label: Background Size
      description: Select the image background size.
      default: "contain auto"